Update transactions
NightfallRollup/nightfall-sdk pull request #17
Opened 2023-06-13 22:07 UTC by druiz0992

## What does this implement/fix? Explain your changes.

## Does this close any currently open issues?

## What commands can I run to test the change? 

## Any other comments?

2023-06-14 07:01 UTC, imagobea requested changes
Hey @druiz0992 amazing work at the speed of light :zap: 

Requesting changes because i think in User.transfer you added salt instead of regulator (?) Please take a look (or maybe I'm still asleep)

Have left few small suggestions. Let me know when ready for re-review.
Thank you!!

2023-06-14 07:01 UTC, imagobea commented on libs/user/types.ts
> +  providedCommitmentsFee?: string[] | [];
`providedCommitmentsFee` can be added to `UserMakeTransaction` since it's common to all txs

2023-06-14 07:01 UTC, imagobea commented on libs/user/types.ts
> +  providedCommitmentsFee?: string[] | [];
You can also extract `providedCommitmentsFee` here and add it to `UserL2TokenisationTransaction`

2023-06-14 07:01 UTC, imagobea commented on libs/user/user.ts
> +      salt,
I think here you meant to handle `regulatorUrl`, not `salt` (?)

2023-06-14 07:01 UTC, imagobea commented on libs/user/validations.ts
> +  providedCommitmentsFee: Joi.array().items(Joi.string()) || Joi.array().min(0),
Similar to previous comments on `types` file, please consider extracting `providedCommitmentsFee` into respective objects.

Also, I think the following is enough for the validation:

```
providedCommitments: Joi.array().items(Joi.string())
```

Empty array should pass just fine.
Then in `User` you are applying the default `[]`, but you could also do this here - see `feeWei` as example.

In case it helps, Joi offers a handy [sandbox](https://joi.dev/tester/) (IMO)

2023-06-14 07:01 UTC, imagobea commented on package.json
> +  "version": "1.2.1",
Perhaps `1.3.0`
The third digit is for bug fixes, and here we are extending functionality (even if we just added a few params here and there..)
What do you think?

2023-06-14 10:52 UTC, druiz0992 commented on libs/user/types.ts
> +  providedCommitmentsFee?: string[] | [];
ok

2023-06-14 10:52 UTC, druiz0992 commented on libs/user/types.ts
> +  providedCommitmentsFee?: string[] | [];
ok

2023-06-14 10:53 UTC, druiz0992 commented on libs/user/validations.ts
> +  providedCommitmentsFee: Joi.array().items(Joi.string()) || Joi.array().min(0),
didn't know how to do this: `Then in User you are applying the default [], but you could also do this here - see feeWei as example.`. Other suggestion was added.

2023-06-14 10:53 UTC, druiz0992 commented on package.json
> +  "version": "1.2.1",
ok

2023-06-14 12:23 UTC, druiz0992 commented on libs/user/user.ts
> +      salt,
Ok

2023-06-16 06:14 UTC, imagobea approved these changes
Thanks for the update @druiz0992 You're good to go

2023-06-16 06:47 UTC, merged